NVIDIA: SAUCE: mm: Fix multi-gen LRU build
Enabling CONFIG_LRU_GEN can trigger the following build error:

mm/vmscan.c:4384:9: error: too few arguments to function 'trace_mm_vmscan_lru_isolate'
 4384 |         trace_mm_vmscan_lru_isolate(sc->reclaim_idx, sc->order, MAX_LRU_BATCH,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/trace/events/vmscan.h:9,

This was introduced by the backport of commit 316fe43e4d04 ("mm:
multi-gen LRU: reuse some legacy trace events").

Fix by passing all the required arguments to trace_mm_vmscan_lru_isolate().

Fixes: 316fe43e4d04 ("mm: multi-gen LRU: reuse some legacy trace events")
Signed-off-by: Andrea Righi <arighi@nvidia.com>