selftest: kvm: Add amx selftest
commit bf70636d9443c9e0718fd98765ba634e631ed079 upstream.

Backport note: swap -I$(LINUX_HDR_PATH) & -I$(LINUX_TOOL_ARCH_INCLUDE)
in Makefile to fix below issue:

ib/x86_64/processor.c: In function ‘vm_xsave_req_perm’:
lib/x86_64/processor.c:615:15: error: ‘SYS_arch_prctl’ undeclared (first use in this function)
  rc = syscall(SYS_arch_prctl, ARCH_REQ_XCOMP_GUEST_PERM, bit);
               ^~~~~~~~~~~~~~

This selftest covers two aspects of AMX.  The first is triggering #NM
exception and checking the MSR XFD_ERR value.  The second case is
loading tile config and tile data into guest registers and trapping to
the host side for a complete save/load of the guest state.  TMM0
is also checked against memory data after save/restore.

Signed-off-by: Yang Zhong <yang.zhong@intel.com>
Message-Id: <20211223145322.2914028-4-yang.zhong@intel.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
Signed-off-by: Jiawei Gu <gujiawei.will@bytedance.com>